GLOBAL:
    LOG_LEVEL: 2
    DEFAULT_TENSOR_TYPE: torch.cuda.FloatTensor
    EPS: 1.0e-08
    GPU_INDICES:
    - 0
    RANDOM_SEED: 1618033989
    ANOMALY_DETECTION: false
    METHOD_TYPE: MoNeRF
    DATASET_TYPE: DNeRF
MODEL:
    USE_ZERO_CANONICAL: false
    SCALE: 0.5
    RESOLUTION: 128
    CENTER:
    - 0.0
    - 0.0
    - 0.0
    HASHMAP_NUM_LEVELS: 16
    HASHMAP_NUM_FEATURES_PER_LEVEL: 2
    HASHMAP_LOG2_SIZE: 19
    HASHMAP_BASE_RESOLUTION: 16
    HASHMAP_TARGET_RESOLUTION: 2048
    NUM_DENSITY_OUTPUT_FEATURES: 16
    NUM_DENSITY_NEURONS: 64
    NUM_DENSITY_LAYERS: 1
    DIR_SH_ENCODING_DEGREE: 4
    NUM_COLOR_NEURONS: 64
    NUM_COLOR_LAYERS: 2
    NUM_DEFORMATION_NEURONS: 128
    NUM_DEFORMATION_LAYERS: 4
    NUM_TEMPORAL_NEURONS: 64
    NUM_TEMPORAL_LAYERS: 2
    TEMPORAL_ENCODING_LENGTH: 4
    POSITIONAL_ENCODING_LENGTH: 10
    TEMPORAL_BASIS_LENGTH: 16
    USE_TEMPORAL_BASIS: true
RENDERER:
    MAX_SAMPLES: 512
    EXPONENTIAL_STEPS: false
    DENSITY_THRESHOLD: 0.01
TRAINING:
    LOAD_CHECKPOINT: null
    MODEL_NAME: hook
    NUM_ITERATIONS: 30000
    ACTIVATE_TIMING: false
    REQUIRE_GIT_COMMIT: false
    BACKUP:
        FINAL_CHECKPOINT: true
        RENDER_TESTSET: true
        RENDER_TRAINSET: false
        RENDER_VALSET: false
        INTERVAL: -1
        TRAINING_STATE: false
    LOGGING:
        ACTIVATE_WANDB: false
        WANDB_ENTITY: ''
        WANDB_PROJECT: ''
        INTERVAL: -1
        RENDER_OCCUPANCY_GRIDS: false
        INDEX_VALIDATION: -1
        INDEX_TRAINING: -1
    RUN_VALIDATION: false
    BATCH_SIZE: 8192
    WARMUP_STEPS: 1024
    RANDOM_BG: true
    DENSITY_GRID_UPDATE_INTERVAL: 16
    DENSITY_GRID_TEMPORAL_SAMPLES: 20
    LEARNING_RATE_NET: 0.001
    LEARNING_RATE_ENCODING: 0.01
    LEARNING_RATE_DECAY_FACTOR: 0.03333333333333333
    ADAM_EPS: 1.0e-15
    LAMBDA_BG_ENTROPY: 0.01
    LAMBDA_FLOW_MAGNITUDE: 0.001
    LAMBDA_DISTORTION: 0.0
    ALPHA_RAY_SAMPLE_WEIGHT: 1.0
DATASET:
    PATH: dataset/d-nerf/hook
    IMAGE_SCALE_FACTOR: 0.5
    NORMALIZE_RADIUS: 1.5
    NORMALIZE_RECENTER: false
    PRECOMPUTE_RAYS: false
    TO_DEVICE: true
    BACKGROUND_COLOR:
    - 1.0
    - 1.0
    - 1.0
